apiVersion: v1
kind: ConfigMap
metadata:
  name: shipping
  namespace: roboshop
data:
  CART_ENDPOINT: "cart:8080"
  backend_HOST: "mysql"

---

apiVersion: v1
kind: Service
metadata: 
  name: shipping
  namespace: roboshop
spec:
  selector:
    project: roboshop
    component: shipping
    env: dev
    tier: backend
  ports: 
  - protocol: TCP
    port: 8080
    targetPort: 8080

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shipping
  namespace: roboshop
  # these are replica set labels
  labels:
    project: roboshop
    component: shipping
    env: dev
    tier: backend
spec:
  replicas: 1
  selector:
    # these labels are used to select pods
    matchLabels:
      project: roboshop
      component: shipping
      env: dev
      tier: backend
  # pod definition
  template:
    metadata:
      labels:
        project: roboshop
        component: shipping
        env: dev
        tier: backend
    spec:
      containers:
      - name: shipping
        image: someshwarsangaraju/shipping:v1
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: shipping
        ports:
        - name: liveness-port
          containerPort: 8080
        resources:
          requests:
            cpu: "200m"
            memory: "256Mi"
          limits:
            cpu: "400m"
            memory: "512Mi"
        readinessProbe:
          httpGet:
            path: /health
            port: liveness-port
          failureThreshold: 1
          periodSeconds: 15
        livenessProbe:
          httpGet:
            path: /health
            port: liveness-port
          failureThreshold: 1
          periodSeconds: 15
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: shipping
  namespace: roboshop
  labels:
    project: roboshop
    component: shipping
    env: dev
    tier: backend
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: shipping
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70 # 70 is the real value