apiVersion: v1
kind: Service
metadata:
  name: mongodb
  labels:
    project: roboshop
    component: mongodb
    tier: db
spec:
  clusterIP: None
  selector:
    project: roboshop
    component: mongodb
    tier: db
  ports:
  - protocol: TCP
    port: 27017
    targetPort: 27017
---

apiVersion: v1
kind: Service
metadata:
  name: mongodb
  labels:
    project: roboshop
    component: mongodb
    tier: db
spec:
  selector:
    project: roboshop
    component: mongodb
    tier: db
  ports:
  - protocol: TCP
    port: 27017
    targetPort: 27017
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
spec:
  selector:
    matchLabels:
      project: roboshop
      component: mongodb
      tier: db # has to match .spec.template.metadata.labels
  serviceName: "mongodb"
  replicas: 3 # by default is 1
  minReadySeconds: 10 # by default is 0
  template:
    metadata:
      labels:
       project: roboshop
       component: mongodb
       tier: db # has to match .spec.selector.matchLabels
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: mongodb
        image: someshwarsangaraju/mongodb:v1
        volumeMounts:
        - name: www
          mountPath: /usr/share/nginx/html
  volumeClaimTemplates:
  - metadata:
      name: www
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "roboshop-ebs"
      resources:
        requests:
          storage: 1Gi