apiVersion: v1
kind: ConfigMap
metadata:
  name: catalogue
  namespace: roboshop
data:
  MONGO: "true"
  MONGO_URL: "mongodb://mongodb:27017/catalogue"

---
apiVersion: v1
kind: Service
metadata:
  name: catalogue-headless
  namespace: roboshop
spec:
  selector:
    project: roboshop
    component: catalogue
    tier: backend
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalogue
  namespace: roboshop
  labels:
    project: roboshop
    component: catalogue
    tier: backend
spec:
  selector:
    matchLabels:
      project: roboshop
      component: catalogue
      tier: backend
  serviceName: catalogue-headless
  replicas: 1
  template:
    metadata:
      name: catalogue
    spec:
      containers: 
      - name: catalogue
        image: someshwarsangaraju/catalogue:v1
        envFrom:
        - ConfigMapRef:
            name: catalogue
        readinessProbe:
          httpGet:
            port: 8080
            path: /health
          failureThreshold: 1
          periodSeconds: 15
          initialDelaySeconds: 30
        livenessProbe:
          httpGet: 
            path: /health
            port: 8080
          failureThreshold: 1
          initialDelaySeconds: 30
          periodSeconds: 15
        resources:
          request:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "200m"
            memory: "256Mi"
  
---

apiVersion: autoscaling/v2
#apiVersion: autoscaling/v2beta2  # k8s 1.6+ - scale using the largest of multiple metrics
kind: HorizontalPodAutoscaler
metadata:
  name: catalogue
  namespace: roboshop
  labels:
    project: roboshop
    component: catalogue
    tier: backend
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: catalogue
  minReplicas: 1
  maxReplicas: 10
  # targetCPUUtilizationPercentage: 70 # multiple metrics using autoscaling/v2beta2 - remove targetCPUUtilizationPercentage if using this
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
    # - type: Resource
    #   resource:
    #     name: memory
    #     #targetAverageValue: 250M
    #     target:
    #       type: AverageValue
    #       averageValue: 250Mi






